/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author DellVostro
 */

public class Calculatrice extends javax.swing.JFrame {
    
   
private double premierNombre;
private String operateur;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculatrice.class.getName());

    /**
     * Creates new form Calculatrice
     */
    public Calculatrice() {
        initComponents();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMoins = new javax.swing.JButton();
        btnFois = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEgal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculatrice");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(400, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtDisplay.setEditable(false);
        txtDisplay.setBackground(new java.awt.Color(255, 255, 255));
        txtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.addActionListener(this::txtDisplayActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(4, 5, 2, 2));

        btn7.setBackground(new java.awt.Color(51, 153, 255));
        btn7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);
        jPanel2.add(btn7);

        btn8.setBackground(new java.awt.Color(51, 153, 255));
        btn8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.addActionListener(this::btn8ActionPerformed);
        jPanel2.add(btn8);

        btn9.setBackground(new java.awt.Color(51, 153, 255));
        btn9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);
        jPanel2.add(btn9);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(153, 153, 153));
        btnClear.setText("C");
        btnClear.addActionListener(this::btnClearActionPerformed);
        jPanel2.add(btnClear);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 153, 153));
        jButton4.setText("<--");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel2.add(jButton4);

        btn4.setBackground(new java.awt.Color(51, 153, 255));
        btn4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);
        jPanel2.add(btn4);

        btn5.setBackground(new java.awt.Color(51, 153, 255));
        btn5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);
        jPanel2.add(btn5);

        btn6.setBackground(new java.awt.Color(51, 153, 255));
        btn6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);
        jPanel2.add(btn6);

        btnDivision.setBackground(new java.awt.Color(102, 102, 102));
        btnDivision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDivision.setForeground(new java.awt.Color(255, 255, 255));
        btnDivision.setText("÷");
        btnDivision.addActionListener(this::btnDivisionActionPerformed);
        jPanel2.add(btnDivision);

        btnPlus.setBackground(new java.awt.Color(102, 102, 102));
        btnPlus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlus.setForeground(new java.awt.Color(255, 255, 255));
        btnPlus.setText("+");
        btnPlus.addActionListener(this::btnPlusActionPerformed);
        jPanel2.add(btnPlus);

        btn1.setBackground(new java.awt.Color(51, 153, 255));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.addActionListener(this::btn1ActionPerformed);
        jPanel2.add(btn1);

        btn2.setBackground(new java.awt.Color(51, 153, 255));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.addActionListener(this::btn2ActionPerformed);
        jPanel2.add(btn2);

        btn3.setBackground(new java.awt.Color(51, 153, 255));
        btn3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.addActionListener(this::btn3ActionPerformed);
        jPanel2.add(btn3);

        btnMoins.setBackground(new java.awt.Color(102, 102, 102));
        btnMoins.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoins.setForeground(new java.awt.Color(255, 255, 255));
        btnMoins.setText("-");
        btnMoins.addActionListener(this::btnMoinsActionPerformed);
        jPanel2.add(btnMoins);

        btnFois.setBackground(new java.awt.Color(102, 102, 102));
        btnFois.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFois.setForeground(new java.awt.Color(255, 255, 255));
        btnFois.setText("*");
        btnFois.addActionListener(this::btnFoisActionPerformed);
        jPanel2.add(btnFois);

        btn0.setBackground(new java.awt.Color(51, 153, 255));
        btn0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn0.setForeground(new java.awt.Color(255, 255, 255));
        btn0.setText("0");
        btn0.addActionListener(this::btn0ActionPerformed);
        jPanel2.add(btn0);

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(".");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("%");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("±");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3);

        btnEgal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEgal.setForeground(new java.awt.Color(153, 153, 153));
        btnEgal.setText("=");
        btnEgal.addActionListener(this::btnEgalActionPerformed);
        jPanel2.add(btnEgal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtDisplay)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        premierNombre = Double.parseDouble(txtDisplay.getText());
operateur = "+";
txtDisplay.setText(txtDisplay.getText() + " + ");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        txtDisplay.setText(txtDisplay.getText() + "7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + "8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + "1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       txtDisplay.setText(txtDisplay.getText() + "2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
       txtDisplay.setText(txtDisplay.getText() + "3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + "4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
       txtDisplay.setText(txtDisplay.getText() + "5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + "6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtDisplay.setText(txtDisplay.getText() + "9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
      txtDisplay.setText(txtDisplay.getText() + "0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnMoinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoinsActionPerformed
   premierNombre = Double.parseDouble(txtDisplay.getText());
operateur = "-";
txtDisplay.setText(txtDisplay.getText() + " - ");
    }//GEN-LAST:event_btnMoinsActionPerformed

    private void btnFoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFoisActionPerformed
premierNombre = Double.parseDouble(txtDisplay.getText());
operateur = "*";
txtDisplay.setText(txtDisplay.getText() + " * ");
    }//GEN-LAST:event_btnFoisActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        premierNombre = Double.parseDouble(txtDisplay.getText());
operateur = "/";
txtDisplay.setText(txtDisplay.getText() + " / ");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgalActionPerformed
    String texte = txtDisplay.getText();

String deuxiemePartie = texte.substring(texte.lastIndexOf(" ") + 1);

double deuxiemeNombre = Double.parseDouble(deuxiemePartie);

double resultat = 0;

switch (operateur) {
    case "+":
        resultat = premierNombre + deuxiemeNombre;
        break;

    case "-":
        resultat = premierNombre - deuxiemeNombre;
        break;

    case "*":
        resultat = premierNombre * deuxiemeNombre;
        break;

    case "/":
        if (deuxiemeNombre == 0) {
            txtDisplay.setText("Erreur");
            return;
        }
        resultat = premierNombre / deuxiemeNombre;
        break;
}

//txtDisplay.setText(String.valueOf(resultat));
if (resultat == (long) resultat) {
    txtDisplay.setText(String.valueOf((long) resultat));
} else {
    txtDisplay.setText(String.valueOf(resultat));
}
    }//GEN-LAST:event_btnEgalActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
     txtDisplay.setText("");
premierNombre = 0;
operateur = "";
    }//GEN-LAST:event_btnClearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String texte = txtDisplay.getText();

int dernierePositionOperateur = -1;

if (texte.contains(" + ")) {
    dernierePositionOperateur = texte.lastIndexOf(" + ");
} else if (texte.contains(" - ")) {
    dernierePositionOperateur = texte.lastIndexOf(" - ");
} else if (texte.contains(" * ")) {
    dernierePositionOperateur = texte.lastIndexOf(" * ");
} else if (texte.contains(" / ")) {
    dernierePositionOperateur = texte.lastIndexOf(" / ");
}

String nombreActuel;

if (dernierePositionOperateur != -1) {
    nombreActuel = texte.substring(dernierePositionOperateur + 3);
} else {
    nombreActuel = texte;
}

if (!nombreActuel.contains(".")) {
    txtDisplay.setText(texte + ".");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       double nombre = Double.parseDouble(txtDisplay.getText());
double resultat = premierNombre * nombre / 100;
txtDisplay.setText(String.valueOf(resultat));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       if (!txtDisplay.getText().isEmpty()) {
    double nombre = Double.parseDouble(txtDisplay.getText());
    nombre = -nombre;
    txtDisplay.setText(String.valueOf(nombre));
}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String texte = txtDisplay.getText();

if (!texte.isEmpty()) {
    txtDisplay.setText(texte.substring(0, texte.length() - 1));
}
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculatrice().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnEgal;
    private javax.swing.JButton btnFois;
    private javax.swing.JButton btnMoins;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
